describe("MiniStore", function()
  it("can be required", function()
    assert.has_no.errors(function()
      require("ministore")
    end)
  end)

  it("provides api module", function()
    assert.has_no.errors(function()
      require("ministore.api")
    end)
  end)

  it("provides ui module", function()
    assert.has_no.errors(function()
      require("ministore.ui")
    end)
  end)

  it("provides config module", function()
    assert.has_no.errors(function()
      require("ministore.config")
    end)
  end)
end)